### PR TITLE
Add CMake build

### PR DESCRIPTION
**Pull request by olibre**

### CODE REVIEW

**Comment by gdamore** [comment]
This looks awesome.  I am going to do some follow up work to verify this all works before I merge.  I will probably add Travis CI integration. :)

**Comment by reqshark** [comment]
travis is nice but circleCI builds faster

**Comment by gdamore** [comment]
@reqshark that may be... but CircleCI 2.0 is more complex to setup (requiring you to select a base docker image, or build one with dependencies already present), and does not support iOS.  Their stance on open source software is a bit unclear -- they have a blog from several years ago claiming that they added 3 free workers for all open source projects, but nothing really official on their website verifying that this policy still holds -- especially with their 2.0 effort.

**Comment by reqshark** [comment]
oh yeah looks like 2.0 is a downgrade, nice catch!

**Comment by gdamore** [comment]
Looking at this more closely, there are some things missing that I have to add.  For example, we need to detect and enable large file offsets on some systems, and we'd like to detect and use certain system supplied functions (strlcpy, vasprintf, etc.) . Stay tuned.

**Comment by gdamore** [comment]
Fixed in 273e9dc9848d588fad34d16f7122990dd4e4ab7f

(I made follow up changes to further enhance things.)

**Comment by gdamore** [comment]
Note that adding a travis build and a test suite to match would be nice!

**Pull request closed without merging**
